### ISSUE TITLE
require taco.json from another project fails

### ISSUE THREAD

**Issue by 11lein** [Chuxel/taco-team-build#1]
I tried using this template
https://visualstudiogallery.msdn.microsoft.com/407fc1f8-538b-4beb-b2b2-69afcb6fbd96

It has two projects
- App/
   - ts/
   - www/
   - ...
   - taco.json
- Tasks/
   - bower/
   - node_modules/
   - ...
   - gulpfile.js
   - package.json

[gulpfile.js]
var cordovaBuild = require("taco-team-build");

cordovaBuild.configure({
    projectPath: '../App'
}); 

gulp.task('build', function () {
    return cordovaBuild.buildProject('android');
});

Build task will fail in your setupCordova while require '../App/taco,json'
Error: Cannot find module '..\App\taco.json'

**Comment by 11lein** [comment]
*Workaround*
set also the cordova version in configure 

cordovaBuild.configure({
cordovaVersion: "5.0.0",
projectPath: '../App'
});

**Comment by Chuxel** [comment]
Thanks - I will take a look.

**Comment by Chuxel** [comment]
Added a fix.  Reference "https://github.com/Chuxel/taco-team-build/archive/0.0.5.tar.gz" in your package.json file instead of "http://aka.ms/tacoteambuild-rel" and let me know if you hit any additional issues.

**Comment by 11lein** [comment]
Thanks - your fix works :-)
